### ISSUE TITLE
api_key recommendation

### ISSUE THREAD

**Issue by jbkunst** [amsantac/SkyWatchr#1]
Hi! I see your nice package in r-project en español and I come with a recommedation:

Instead of give the api_key as argument in every function call, you can read it from options. You can set once per session and call it inside of every function. For example.

```
library(SkyWatchr)
options(SkyWatchr.apikey = 'thelongapikey')
```

And in the `querySW` function:
```
querySW <- function(api_key, time_period, longitude_latitude, ... ){

...
...

  api_key <- getOption("SkyWatchr.apikey")

  if(is.null(api_key)) {
    message("You need set an api Key via options(SkyWatchr.apikey = 'thelongapikey')")
  }  

  query <- GET(paste0(URL, "?"), add_headers('Accept' = 'application/json', 'x-api-key' = api_key))

...
...
}
```

So the users of your package will have a cleaner code.

**Comment by amsantac** [comment]
Thank you very much Joshua. Reading the api key from the options would be a great improvement. Thanks a lot for contributing the code. I'll add this feature ASAP

**Comment by amsantac** [comment]
@jbkunst I've added the feature for setting the SkyWatchr.apikey option for users convenience. This update (version 0.5-1 ) is available on CRAN now. Thank you very much Joshua for your contribution

**Comment by jbkunst** [comment]
You're welcome. Thank to you for the package :D
