### ISSUE TITLE
large amount of data downloaded in downloadSW sample code

### ISSUE THREAD

**Issue by mapMakingActuary** [amsantac/SkyWatchr#2]
Can you clean up the sample code in the 'downloadSW' example or at least warn people testing the package that it will download a big chunk of data. 

res <- querySW(time_period = "2015-06", longitude_latitude = "48.676074,31.321119", data_level = 3)
sum(res$size_kb) = 57,873,308

**Comment by amsantac** [comment]
Done. I added a warning to the example in the downloadSW documentation file. Thanks
